version: '3'
services:
  postgres:
    image: postgres
    container_name: ThreeTree
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: atidb
      POSTGRES_PASSWORD: atidb
    ports:
      - "5432:5432"


  backend:
    container_name: threetree-backend
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: ./mvnw package
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    build:
      context: ../frontend
      dockerfile: DockerFileFrontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
